#tests that shell builds on multiple platforms
name: Build Cross-Platform

on:
    push:
        paths:
        - '**/*.cpp'
        - '**/*.c'
        - '**/*.h'
        - '**/*.hpp'
        - '**/*.yml'
    workflow_dispatch:

jobs:
    Ubuntu-Compilation:
        name: Compile On Ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Shell Compilation (Ubuntu)
              run: g++ -Wall -Wextra -fdiagnostics-color=always 439shell.cpp -o ./439shell

    Windows-Compilation:
        name: Compile On Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Shell Compilation (Windows)
              run: g++ -Wall -Wextra -fdiagnostics-color=always 439shell.cpp -o ./439shell

    MacOS-Compilation:
        name: Compile On MacOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Shell Compilation (MacOS)
              run: clang++ -std=c++11 -Wall -Wextra -fdiagnostics-color=always 439shell.cpp -o ./439shell
