#This tests that shell builds on both windows and linux
name: Build

on:
    push:
    workflow_dispatch:

jobs:
    Ubuntu-Compilation:
        name: Compile On Ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Shell Compilation (ubuntu)
              run: g++ -Wall -Wextra -fdiagnostics-color=always main.cpp -o ./main

    Windows-Compilation:
        name: Compile On Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Shell Compilation (windows)
              run: g++ -Wall -Wextra -fdiagnostics-color=always main.cpp -o ./main
