# This workflow tests the compiled shell program after it has been built.
# It downloads the artifacts from the 'Build Cross-Platform' workflow
# and runs basic tests on each platform.
name: Test Shell Program

on:
    workflow_run:
        workflows: ["Build Cross-Platform"]
        types: [completed]

jobs:
    Test-Ubuntu:
        name: Test on Ubuntu
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Download Ubuntu artifact
              uses: actions/download-artifact@v4
              with:
                  name: ubuntu-439shell
                  github-token: ${{ secrets.GITHUB_TOKEN }} # Token is required for downloading artifacts from other workflow runs
                  run-id: ${{ github.event.workflow_run.id }} # ID of the workflow run that triggered this one

            - name: Make shell executable (Ubuntu)
              run: chmod +x ./439shell

            - name: ls
              run: ./439shell ls

            - run: ./439shell cmd that doesnt exist

    Test-Windows:
        name: Test on Windows
        runs-on: windows-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Download Windows artifact
              uses: actions/download-artifact@v4
              with:
                  name: windows-439shell
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ github.event.workflow_run.id }}

            - name: Run Windows shell test
              shell: cmd # Use cmd for Windows if needed, or powershell/bash
              run: |
                  echo "Running tests for Windows shell..."
                  REM Replace with your actual test commands
                  .\439shell.exe --version || .\439shell.exe help || (echo exit 0 | .\439shell.exe)
                  echo "Windows tests finished."

    Test-MacOS:
        name: Test on MacOS
        runs-on: macos-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Download MacOS artifact
              uses: actions/download-artifact@v4
              with:
                  name: macos-439shell
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ github.event.workflow_run.id }}

            - name: Make shell executable (MacOS)
              run: chmod +x ./439shell

            - name: Run MacOS shell test
              run: |
                  echo "Running tests for MacOS shell..."
                  # Replace with your actual test commands
                  ./439shell --version || ./439shell help || echo "exit 0" | ./439shell
                  echo "MacOS tests finished."
